version: '3'

services:
  web:
    build: .
    #command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/geodjango_news_map
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  #redis:
  #  image: redis:alpine
  #  ports:
  #    - "6379:6379"
