# Generated by Django 2.2.5 on 2019-11-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodjango_news_map_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='source',
            name='_api_id',
        ),
        migrations.RemoveField(
            model_name='source',
            name='_category',
        ),
        migrations.RemoveField(
            model_name='source',
            name='_country_alpha_code',
        ),
        migrations.RemoveField(
            model_name='source',
            name='_description',
        ),
        migrations.AlterField(
            model_name='source',
            name='_country',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='source',
            name='_language',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='source',
            name='_url',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='_categories',
            field=models.ManyToManyField(to='geodjango_news_map_web.Category'),
        ),
    ]
