# Generated by Django 2.2.5 on 2019-10-08 11:09

from django.db import migrations, models
import geodjango_news_map.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('geodjango_news_map_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryresultset',
            name='_choropleth',
            field=models.FileField(default=None, storage=geodjango_news_map.storage_backends.MediaStorage(), upload_to=''),
        ),
    ]
