# Generated by Django 2.2.5 on 2019-09-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodjango_news_map_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryresultset',
            name='_date_last_modified',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
