# Generated by Django 2.2.5 on 2019-09-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodjango_news_map_web', '0002_queryresultset__date_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='_body',
            field=models.CharField(max_length=25000),
        ),
    ]
