# Generated by Django 2.2.5 on 2019-10-09 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodjango_news_map_web', '0002_auto_20191008_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryresultset',
            name='_choropleth',
            field=models.TextField(blank=True, max_length=2000000),
        ),
    ]
