# Generated by Django 2.2.7 on 2019-11-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodjango_news_map_web', '0003_auto_20191116_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='_url',
            field=models.URLField(blank=True, default='', max_length=150),
        ),
    ]
