# Generated by Django 2.2.5 on 2019-09-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodjango_news_map_web', '0003_auto_20190920_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='_body',
            field=models.CharField(blank=True, default='', max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='_title',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
