# Generated by Django 2.2.7 on 2019-11-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodjango_news_map_web', '0004_auto_20191120_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryresultset',
            name='_article_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='queryresultset',
            name='_article_data_len',
            field=models.IntegerField(default=0),
        ),
    ]
