# Generated by Django 2.2.7 on 2019-11-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodjango_news_map_web', '0005_auto_20191122_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='_verified',
            field=models.BooleanField(default=False),
        ),
    ]
